# Generated by Django 3.2.6 on 2022-12-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_job_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateskill',
            unique_together={('candidate', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='jobskill',
            unique_together={('job', 'skill')},
        ),
    ]
